branches:
  only:
    - beta

language: node_js

node_js:
  - 5.5

before_install:
  - openssl aes-256-cbc -K $encrypted_622f743b98c0_key -iv $encrypted_622f743b98c0_iv -in .travis/warcraftlfg.enc -out .travis/warcraftlfg -d

install:
  - npm install -g mocha grunt-cli bower
  - npm install

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/warcraftlfg # this key should have push access
  - ssh-add .travis/warcraftlfg
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh warcrafthub@warcraftlfg.com 'cd warcraft-lfg-testing;git pull origin beta;npm update;bower install;grunt prod'

notifications:
  slack: warcraftlfg:JV8vgwSfBUw1rSHCxlxlOUF3